name: PR Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven and run tests
        run: mvn -B verify -f src/test/java/intens/api/praksa2022/Praksa2022ApplicationTests.java

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: src/test/java/intens/api/praksa2022/target/surefire-reports
